---
- hosts: tag_Env_dev
  sudo: yes
  remote_user: ubuntu
  vars:
    env: 'dev'
    app: 'devops_blog'
  tasks:
    - name: Install nginx
      apt: pkg="nginx" state=installed update_cache=yes

    - name: Install uwsgi
      apt: pkg="uwsgi" state=installed update_cache=yes

    - name: Deploy application code
      git:
        repo: "git@github.com/shadowbrain/{{ app }}"
        dest: "/var/www/{{ app }}"
        version: "{{ git_branch | default('master') }}"
        accept_hostkey: yes

    - name: Configure nginx to uwsgi
      template:
        src: nginx-uwsgi.conf.j2
        dest: /etc/nginx/sites-enabled/uwsgi.conf
        owner: root
        group: root
        mode: 0644

    - name: Restart nginx
      service: name=nginx state=restarted

    - name: Launch uwsgi app
      command: uwsgi -s /tmp/uwsgi.socket -w application:app
