---
- hosts: tag_Env_dev
  sudo: yes
  remote_user: ubuntu
  vars:
    env: 'dev'
    app: 'devops_blog'
  tasks:
    - name: Install nginx
      apt: pkg="nginx" state=installed
    - name: Install uwsgi
      apt: pkg="uwsgi" state=installed
    - name: Deploy application code
      git:
        repo: "git@github.com/vitalco/{{ app }}"
        dest: "/home/ubuntu/{{ app }}"
        version: "{{ git_branch | default('master') }}"
        accept_hostkey: yes
